config/routes.rb
Rails.application.routes.draw do
  root to: "organizations#index"

  resources :organizations, only: [:index, :show] do
    collection do
      get "filter"
    end
  end
end

app/models/eligibility.rb
class Eligibility < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :organization_eligibilities
  has_many :organizations, through: :organization_eligibilities

  attr_accessor :selected

  validates :name, presence: true, uniqueness: true

  def set_selected(params)
    # make sure case insensitive keys work
    # hence downcase
    if params
      down_params = params.map {|k, v| [k.downcase, v] }.to_h
      @selected = down_params.key?(name.downcase)
    end
  end

  def selected?
    @selected || false
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :organization

  validates :address, :city, :state, :zipcode, presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  has_many :locations
  has_many :organization_eligibilities
  has_many :eligibilities, through: :organization_eligibilities

  def self.filter_by_eligibilities(eligibilities, opts = {})
    selected_eligibilities = (eligibilities || []).select { |el| el.selected? }
    names = selected_eligibilities.map(&:name).map(&:downcase)
    opts = opts || {and: false}

    if !selected_eligibilities.empty?

      if opts[:and] == true
        where(id: Eligibility
                .joins(:organization_eligibilities)
                .select(:organization_id)
                .where("lower(name) in (?)", names)
                .group(:organization_id)
                .having("count(organization_id) = ?", names.length))
        .order(:name)
      else
        where(id: Eligibility
                  .joins(:organization_eligibilities)
                  .where("lower(name) in (?)", names)
                  .select(:organization_id))
        .order(:name)
      end
    else
      order(:name)
    end
  end
end

app/models/organization_eligibility.rb
class OrganizationEligibility < ActiveRecord::Base
  belongs_to :organization
  belongs_to :eligibility

  validates :organization, :eligibility, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @eligibilities = Eligibility.order(:name)
    @eligibilities.each { |el| el.set_selected(params) }
    @and = params.key?(:and) && params[:and] == "true"

    @organizations = Organization.filter_by_eligibilities(@eligibilities, { and: @and })
  end

  def show
    @show_eligibilities = true
    @organization = Organization.find(params[:id]).decorate
  end

  def filter
    if params && params[:eligibilities]
      res = params[:eligibilities].map { |el| [el, "yes"] }.to_h
    else
      res = {}
    end

    res[:and] = params.key?(:and) && params[:and] == "and"
    res[:action] = "index"
    redirect_to res
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eligibilities/_filter.html.erb
<div class="pb2">
  <%= form_tag "/organizations/filter", method: :get do %>
    <% @eligibilities.each do |el| %>
      <div class="eligibility filter card">
        <label class="custom-checkbox-label">
          <%= check_box_tag "eligibilities[]", el.name, el.selected? %>
          <span class="custom-checkbox"></span>
          <span class="name"><%= el.name %></span>
        </label>
      </div>
    <% end %>
    <div class="pb1">
      <%= check_box_tag "and", "and", @and %> Only results with all checked services
    </div>
    <div class="pb4">
      <%= submit_tag "Apply Filter", id: "apply_filter", class: "btn btn-primary pull-right-lg" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullStackChallenge</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
</head>
<body>

<div class="flashes">
  <% if flash[:success] %>
    <p class="success"><%= flash[:success] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert"><%= alert %></p>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/organizations/_organization.html.erb
<div class="card">
  <div class="title">
    <%= link_to(organization.decorate.name, organization_path(organization)) %>
  </div>
  <div class="subtitle">
    <% organization.locations.each do |location| %>
      <div><%= location.decorate.address %></div>
    <% end %>
  </div>
  <% if @show_eligibilities %>
    <div class="eligibilities">
      <% organization.eligibilities.each do |eligibility| %>
        <span class="label label-default"><%= eligibility.name %></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/organizations/index.html.erb
<% provide(:title, "All Organizations") %>

<div class="jumbotron primary">
  <div class="container">
    <h4>Resource Search</h4>
  </div>
</div>

<div class="container">
  <h4 class="h4">Filters</h4>
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <%= render partial: "eligibilities/filter" %>
    </div>
    <div class="col-xs-12 col-sm-8 col-sm-offset-1">
      <%= render @organizations %>
    </div>
  </div>

</div>

app/views/organizations/show.html.erb
<% provide(:title, @organization.name) %>

<div class="jumbotron primary">
  <div class="container">
    <h4>Organization</h4>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= render @organization %>

      <%= link_to("Back to All Organizations", organizations_path) %>
    </div>
  </div>
</div>